# Generated by Django 4.1.7 on 2023-05-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emoji",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=50)),
                ("tag_name", models.CharField(max_length=50)),
                ("emoji_tag", models.CharField(max_length=50)),
                ("emoji_url", models.CharField(max_length=256)),
                ("emoji", models.BinaryField()),
                ("set_num", models.IntegerField()),
            ],
            options={"db_table": "emoji",},
        ),
        migrations.CreateModel(
            name="Style",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=50)),
                ("tag_name", models.CharField(max_length=50)),
                ("img_url", models.CharField(max_length=256)),
                ("img", models.BinaryField()),
            ],
            options={"db_table": "style",},
        ),
        migrations.DeleteModel(name="Product",),
    ]
