# Generated by Django 4.1.7 on 2023-05-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_emoji_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emoji", name="emoji", field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name="style", name="img", field=models.BinaryField(),
        ),
    ]
