# Generated by Django 4.1.7 on 2023-05-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_emoji_emoji_alter_style_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emoji",
            name="requestId",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="style",
            name="requestId",
            field=models.CharField(max_length=50),
        ),
    ]
