# Generated by Django 4.1.7 on 2023-05-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_emoji_request_id_alter_style_request_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="emoji", name="set_num", field=models.IntegerField(default=1),
        ),
    ]
