# Generated by Django 4.1.7 on 2023-05-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_emoji_set_num"),
    ]

    operations = [
        migrations.RemoveField(model_name="emoji", name="set_num",),
    ]
