# Generated by Django 4.1.7 on 2023-06-05 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_emoji_set_num"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emoji", old_name="emoji_tag", new_name="emojiTag",
        ),
        migrations.RenameField(
            model_name="emoji", old_name="emoji_url", new_name="emojiUrl",
        ),
        migrations.RenameField(
            model_name="emoji", old_name="set_num", new_name="setNum",
        ),
        migrations.RenameField(
            model_name="emoji", old_name="tag_name", new_name="tagName",
        ),
        migrations.RenameField(
            model_name="style", old_name="img_url", new_name="imgUrl",
        ),
        migrations.RenameField(
            model_name="style", old_name="tag_name", new_name="tagName",
        ),
    ]
