# Generated by Django 4.1.7 on 2023-06-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_rename_emoji_tag_emoji_emojitag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="style", old_name="imgUrl", new_name="tagUrl",
        ),
    ]
