# Generated by Django 4.1.7 on 2023-06-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_style_setnum"),
    ]

    operations = [
        migrations.AddField(
            model_name="emoji",
            name="emojiRequestId",
            field=models.CharField(default="emojiRequestId", max_length=50),
            preserve_default=False,
        ),
    ]
